# Generated by Django 3.0.6 on 2020-05-07 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='mofified',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='mofified',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='mofified',
            new_name='modified',
        ),
    ]
