# Generated by Django 3.0.6 on 2020-05-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200507_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='image',
            new_name='picture',
        ),
    ]
