# Generated by Django 3.0.6 on 2020-05-07 17:55

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200507_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='picture',
            field=stdimage.models.StdImageField(upload_to='team/pictures', verbose_name='Image'),
        ),
    ]
