# Generated by Django 3.0.6 on 2020-05-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200510_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Preco'),
        ),
    ]
